[
  { "id": "MB-ASS-001", "name": "Robotic Arm KUKA-X1", "section": "Assembly", "desc": "Main Chassis Welding Unit", "status": "WORKING" },
  { "id": "MB-ASS-002", "name": "Robotic Arm KUKA-X2", "section": "Assembly", "desc": "Main Chassis Welding Unit", "status": "WORKING" },
  { "id": "MB-ASS-003", "name": "Nut Runner Station A1", "section": "Assembly", "desc": "Torque Fastening - Front Axle", "status": "WORKING" },
  { "id": "MB-ASS-004", "name": "Nut Runner Station A2", "section": "Assembly", "desc": "Torque Fastening - Rear Axle", "status": "WORKING" },
  { "id": "MB-ASS-005", "name": "Glass Fit Robot G1", "section": "Assembly", "desc": "Windshield Automatic Installation", "status": "WORKING" },
  { "id": "MB-ASS-006", "name": "Interior Line Conveyor", "section": "Assembly", "desc": "Dashboard Transport System", "status": "WORKING" },
  { "id": "MB-ASS-007", "name": "Marriage Station 1", "section": "Assembly", "desc": "Body-to-Chassis Integration", "status": "WORKING" },
  { "id": "MB-ASS-008", "name": "Marriage Station 2", "section": "Assembly", "desc": "Body-to-Chassis Integration", "status": "WORKING" },
  { "id": "MB-ASS-009", "name": "Fluid Fill Station", "section": "Assembly", "desc": "Brake/Coolant Injection", "status": "WORKING" },
  { "id": "MB-ASS-010", "name": "Seat Installation Lift", "section": "Assembly", "desc": "Ergonomic Interior Assembly", "status": "WORKING" },
  { "id": "MB-ASS-011", "name": "Battery Mount Station", "section": "Assembly", "desc": "EV Battery Pack Integration", "status": "WORKING" },
  { "id": "MB-ASS-012", "name": "Final Trim Press", "section": "Assembly", "desc": "Exterior Trim Application", "status": "WORKING" },
  { "id": "MB-ASS-013", "name": "Wheel Mount Robot W1", "section": "Assembly", "desc": "Automatic Wheel Positioning", "status": "WORKING" },
  { "id": "MB-ASS-014", "name": "Wheel Mount Robot W2", "section": "Assembly", "desc": "Automatic Wheel Positioning", "status": "WORKING" },
  { "id": "MB-ASS-015", "name": "Roof Laser Welder", "section": "Assembly", "desc": "High-Precision Roof Sealing", "status": "WORKING" },
  { "id": "MB-ASS-016", "name": "Door Seal Press", "section": "Assembly", "desc": "Weather-strip Application", "status": "WORKING" },
  { "id": "MB-ASS-017", "name": "Underbody Bolting A", "section": "Assembly", "desc": "Automated Fastening System", "status": "WORKING" },
  { "id": "MB-ASS-018", "name": "Underbody Bolting B", "section": "Assembly", "desc": "Automated Fastening System", "status": "WORKING" },
  { "id": "MB-ASS-019", "name": "Front Fascia Station", "section": "Assembly", "desc": "Bumper and Grille Assembly", "status": "WORKING" },
  { "id": "MB-ASS-020", "name": "Harness Router H1", "section": "Assembly", "desc": "Wire Harness Installation", "status": "WORKING" },
  { "id": "MB-ASS-021", "name": "Harness Router H2", "section": "Assembly", "desc": "Wire Harness Installation", "status": "WORKING" },
  { "id": "MB-ASS-022", "name": "Tire Pressure Station", "section": "Assembly", "desc": "Automatic Air Calibration", "status": "WORKING" },
  { "id": "MB-ASS-023", "name": "Sunroof Fit Unit", "section": "Assembly", "desc": "Glass Roof Alignment", "status": "WORKING" },
  { "id": "MB-ASS-024", "name": "Mirror Mount Robot", "section": "Assembly", "desc": "Side Mirror Installation", "status": "WORKING" },
  { "id": "MB-ASS-025", "name": "Emblem Press", "section": "Assembly", "desc": "Mercedes-Benz Star Applicator", "status": "WORKING" },
  { "id": "MB-ASS-026", "name": "Headlight Aiming Cell", "section": "Assembly", "desc": "Dynamic Beam Alignment", "status": "WORKING" },
  { "id": "MB-ASS-027", "name": "Sound Deadening Robot", "section": "Assembly", "desc": "Insulation Spray Unit", "status": "WORKING" },
  { "id": "MB-ASS-028", "name": "Brake Line Bender", "section": "Assembly", "desc": "Hydraulic Line Forming", "status": "WORKING" },
  { "id": "MB-ASS-029", "name": "Exhaust Lift Unit", "section": "Assembly", "desc": "Exhaust System Positioning", "status": "WORKING" },
  { "id": "MB-ASS-030", "name": "Fuel Tank Station", "section": "Assembly", "desc": "Reservoir Mounting Unit", "status": "WORKING" },
  { "id": "MB-ASS-031", "name": "Cockpit Module Lift", "section": "Assembly", "desc": "Heavy Dash Module Inserter", "status": "WORKING" },
  { "id": "MB-ASS-032", "name": "Center Console Unit", "section": "Assembly", "desc": "Internal Storage Assembly", "status": "WORKING" },
  { "id": "MB-ASS-033", "name": "Floor Carpet Press", "section": "Assembly", "desc": "Precision Liner Fitting", "status": "WORKING" },
  { "id": "MB-ASS-034", "name": "Steering Column Tool", "section": "Assembly", "desc": "Control Module Fastener", "status": "WORKING" },
  { "id": "MB-ASS-035", "name": "Airbag Test Unit", "section": "Assembly", "desc": "Deployment Circuit Check", "status": "WORKING" },
  { "id": "MB-ASS-036", "name": "Wiper Motor Station", "section": "Assembly", "desc": "Drive Unit Installation", "status": "WORKING" },
  { "id": "MB-ASS-037", "name": "Speaker Fit Robot", "section": "Assembly", "desc": "Audio System Installation", "status": "WORKING" },
  { "id": "MB-ASS-038", "name": "Trunk Liner Unit", "section": "Assembly", "desc": "Rear Storage Preparation", "status": "WORKING" },
  { "id": "MB-ASS-039", "name": "Hood Latch Station", "section": "Assembly", "desc": "Locking Mechanism Fit", "status": "WORKING" },
  { "id": "MB-ASS-040", "name": "Badging Station B2", "section": "Assembly", "desc": "Model Designation Press", "status": "WORKING" },
  { "id": "MB-PNT-001", "name": "E-Coat Dip Tank", "section": "Paint Shop", "desc": "Anti-Corrosion Bath", "status": "WORKING" },
  { "id": "MB-PNT-002", "name": "Drying Oven 1", "section": "Paint Shop", "desc": "Curing Thermal Unit", "status": "WORKING" },
  { "id": "MB-PNT-003", "name": "Spray Booth Alpha", "section": "Paint Shop", "desc": "Base Coat Robot", "status": "WORKING" },
  { "id": "MB-PNT-004", "name": "Spray Booth Beta", "section": "Paint Shop", "desc": "Clear Coat Robot", "status": "WORKING" },
  { "id": "MB-PNT-005", "name": "Sanding Robot S1", "section": "Paint Shop", "desc": "Surface Preparation Unit", "status": "WORKING" },
  { "id": "MB-PNT-006", "name": "Sealer Robot S2", "section": "Paint Shop", "desc": "Underbody Sealing Unit", "status": "WORKING" },
  { "id": "MB-PNT-007", "name": "Air Filtration U1", "section": "Paint Shop", "desc": "Cleanroom Ventilation", "status": "WORKING" },
  { "id": "MB-PNT-008", "name": "Mixing Station M1", "section": "Paint Shop", "desc": "Pigment/Solvent Blending", "status": "WORKING" },
  { "id": "MB-PNT-009", "name": "Primer Robot P1", "section": "Paint Shop", "desc": "Initial Layer Application", "status": "WORKING" },
  { "id": "MB-PNT-010", "name": "Quality Light Tunnel", "section": "Paint Shop", "desc": "Visual Defect Inspection", "status": "WORKING" },
  { "id": "MB-PNT-011", "name": "Paint Pump Unit 1", "section": "Paint Shop", "desc": "High-Pressure Delivery", "status": "WORKING" },
  { "id": "MB-PNT-012", "name": "Paint Pump Unit 2", "section": "Paint Shop", "desc": "High-Pressure Delivery", "status": "WORKING" },
  { "id": "MB-PNT-013", "name": "Sludge Separator", "section": "Paint Shop", "desc": "Wastewater Treatment", "status": "WORKING" },
  { "id": "MB-PNT-014", "name": "Flash-off Zone 1", "section": "Paint Shop", "desc": "Ambient Solvent Evaporation", "status": "WORKING" },
  { "id": "MB-PNT-015", "name": "Wax Injection Unit", "section": "Paint Shop", "desc": "Cavity Anti-Rust Spray", "status": "WORKING" },
  { "id": "MB-PNT-016", "name": "Inspection Deck A", "section": "Paint Shop", "desc": "Manual Polish/Touch-up", "status": "WORKING" },
  { "id": "MB-PNT-017", "name": "Conveyor Line P1", "section": "Paint Shop", "desc": "Wet-transfer System", "status": "WORKING" },
  { "id": "MB-PNT-018", "name": "Conveyor Line P2", "section": "Paint Shop", "desc": "Wet-transfer System", "status": "WORKING" },
  { "id": "MB-PNT-019", "name": "Solvent Recovery U1", "section": "Paint Shop", "desc": "Chemical Recycling Plant", "status": "WORKING" },
  { "id": "MB-PNT-020", "name": "Burn-off Oven", "section": "Paint Shop", "desc": "Skid Cleaning System", "status": "WORKING" },
  { "id": "MB-PNT-021", "name": "Robot Atomizer A1", "section": "Paint Shop", "desc": "Electrostatic Bell Unit", "status": "WORKING" },
  { "id": "MB-PNT-022", "name": "Robot Atomizer A2", "section": "Paint Shop", "desc": "Electrostatic Bell Unit", "status": "WORKING" },
  { "id": "MB-PNT-023", "name": "Robot Atomizer A3", "section": "Paint Shop", "desc": "Electrostatic Bell Unit", "status": "WORKING" },
  { "id": "MB-PNT-024", "name": "Robot Atomizer A4", "section": "Paint Shop", "desc": "Electrostatic Bell Unit", "status": "WORKING" },
  { "id": "MB-PNT-025", "name": "Dust Collector U1", "section": "Paint Shop", "desc": "HEPA Intake Filter", "status": "WORKING" },
  { "id": "MB-ENG-001", "name": "Crankshaft Press", "section": "Engine Prep", "desc": "Heavy Hydraulic Alignment", "status": "WORKING" },
  { "id": "MB-ENG-002", "name": "Piston Inserter P1", "section": "Engine Prep", "desc": "Precision Alignment Tool", "status": "WORKING" },
  { "id": "MB-ENG-003", "name": "Cylinder Head Bolt", "section": "Engine Prep", "desc": "Multi-Spindle Torque", "status": "WORKING" },
  { "id": "MB-ENG-004", "name": "Leak Test Cell 1", "section": "Engine Prep", "desc": "Pressure Decay Verification", "status": "WORKING" },
  { "id": "MB-ENG-005", "name": "Cold Test Rig", "section": "Engine Prep", "desc": "Non-Combustion Run Test", "status": "WORKING" },
  { "id": "MB-ENG-006", "name": "Flywheel Press", "section": "Engine Prep", "desc": "Mechanical Friction Fit", "status": "WORKING" },
  { "id": "MB-ENG-007", "name": "Oil Fill Pump", "section": "Engine Prep", "desc": "Metered Lubricant Injection", "status": "WORKING" },
  { "id": "MB-ENG-008", "name": "Valve Lash Adjuster", "section": "Engine Prep", "desc": "Automated Clearance Setup", "status": "WORKING" },
  { "id": "MB-ENG-009", "name": "Timing Chain Tool", "section": "Engine Prep", "desc": "Synchronous Drive Align", "status": "WORKING" },
  { "id": "MB-ENG-010", "name": "Camshaft Grinder", "section": "Engine Prep", "desc": "Precision Profile Finisher", "status": "WORKING" },
  { "id": "MB-ENG-011", "name": "Engine Conveyor E1", "section": "Engine Prep", "desc": "Power-and-Free Rail", "status": "WORKING" },
  { "id": "MB-ENG-012", "name": "Turbocharger Mount", "section": "Engine Prep", "desc": "Induction System Fit", "status": "WORKING" },
  { "id": "MB-ENG-013", "name": "Alternator Torque T1", "section": "Engine Prep", "desc": "Accessory Fastening", "status": "WORKING" },
  { "id": "MB-ENG-014", "name": "Belt Tensioner Unit", "section": "Engine Prep", "desc": "Serpentine Belt Calibration", "status": "WORKING" },
  { "id": "MB-ENG-015", "name": "Starter Motor Test", "section": "Engine Prep", "desc": "Electrical Engagement Check", "status": "WORKING" },
  { "id": "MB-ENG-016", "name": "Exhaust Manifold Fit", "section": "Engine Prep", "desc": "High-Temp Gasket Seal", "status": "WORKING" },
  { "id": "MB-ENG-017", "name": "Sensors Plug-in Robot", "section": "Engine Prep", "desc": "ECU Interface Connector", "status": "WORKING" },
  { "id": "MB-ENG-018", "name": "Fuel Rail Inserter", "section": "Engine Prep", "desc": "Direct Injection Mount", "status": "WORKING" },
  { "id": "MB-ENG-019", "name": "Spark Plug Torque", "section": "Engine Prep", "desc": "Cylinder Ignition Fit", "status": "WORKING" },
  { "id": "MB-ENG-020", "name": "Final Engine Wash", "section": "Engine Prep", "desc": "Ultrasonic Cleaning Cell", "status": "WORKING" },
  { "id": "MB-QC-001", "name": "Laser Scanner 3D", "section": "Quality", "desc": "Body-in-White Variance", "status": "WORKING" },
  { "id": "MB-QC-002", "name": "Rain Test Chamber", "section": "Quality", "desc": "Waterproofing Seal Check", "status": "WORKING" },
  { "id": "MB-QC-003", "name": "Dynamic Dyno 01", "section": "Quality", "desc": "Rolling Road Performance", "status": "WORKING" },
  { "id": "MB-QC-004", "name": "Wheel Align Laser", "section": "Quality", "desc": "Suspension Geometry Check", "status": "WORKING" },
  { "id": "MB-QC-005", "name": "Brake Force Tester", "section": "Quality", "desc": "Stopping Distance Verify", "status": "WORKING" },
  { "id": "MB-QC-006", "name": "Squeak & Rattle Track", "section": "Quality", "desc": "NVH Vibration Analysis", "status": "WORKING" },
  { "id": "MB-QC-007", "name": "Exhaust Emission Lab", "section": "Quality", "desc": "Gas Composition Analyzer", "status": "WORKING" },
  { "id": "MB-QC-008", "name": "Electrical Audit Cell", "section": "Quality", "desc": "Full CAN-bus Diagnostic", "status": "WORKING" },
  { "id": "MB-QC-009", "name": "Gap & Flush Sensor", "section": "Quality", "desc": "Body Panel Alignment", "status": "WORKING" },
  { "id": "MB-QC-010", "name": "Final Finish Deck", "section": "Quality", "desc": "Premium Visual Audit", "status": "WORKING" },
  { "id": "MB-LOG-001", "name": "AGV Carrier 101", "section": "Logistics", "desc": "Autonomous Parts Transport", "status": "WORKING" },
  { "id": "MB-LOG-002", "name": "AGV Carrier 102", "section": "Logistics", "desc": "Autonomous Parts Transport", "status": "WORKING" },
  { "id": "MB-LOG-003", "name": "AGV Carrier 103", "section": "Logistics", "desc": "Autonomous Parts Transport", "status": "WORKING" },
  { "id": "MB-LOG-004", "name": "High-Bay Crane 1", "section": "Logistics", "desc": "ASRS Storage System", "status": "WORKING" },
  { "id": "MB-LOG-005", "name": "High-Bay Crane 2", "section": "Logistics", "desc": "ASRS Storage System", "status": "WORKING" },
  { "id": "MB-LOG-006", "name": "Pallet Wrapper W1", "section": "Logistics", "desc": "Shipping Prep System", "status": "WORKING" },
  { "id": "MB-LOG-007", "name": "Battery Charger S1", "section": "Logistics", "desc": "AGV Power Station", "status": "WORKING" },
  { "id": "MB-LOG-008", "name": "Dock Leveler D1", "section": "Logistics", "desc": "Inbound Loading Bay", "status": "WORKING" },
  { "id": "MB-LOG-009", "name": "Smart Conveyor B2", "section": "Logistics", "desc": "IoT Sortation System", "status": "WORKING" },
  { "id": "MB-LOG-010", "name": "Barcode Scanner Portal", "section": "Logistics", "desc": "Inventory Tracking Gate", "status": "WORKING" }
]